---

- hosts: sensu-server 
  remote_user: corby
  become: true
  become_method: su
  #vars:
    #rabbitmq_pkg: 'http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server-3.6.0-1.noarch.rpm'
  roles:
    - rabbitmq
    - redis
    - role: sensu
      sensu_install_server: true
      sensu_install_api: true

- hosts: sensu-clients
  remote_user: corby
  become: true
  become_method: su
  vars:
    #rabbitmq_pkg: 'http://www.rabbitmq.com/releases/rabbitmq-server/v3.6.0/rabbitmq-server-3.6.0-1.noarch.rpm'
    server__sensu: sensu-server
  roles:
    - rabbitmq
    - role: sensu
      vars: 
        sensu_api_host: "{{ server__sensu }}"
        sensu_rabbitmq_host: "{{ server__sensu }}"
        sensu_redis_host: "{{ server__sensu }}"
