---

galaxy_info:
  author: Robert Readman
  description: A role that installs RabbitMQ
  license: MIT
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - 6
  categories:
    - monitoring
    - networking
dependencies: 
  - role: common/yumrepo
    yumrepo_repos:
      local_install:
        erlang:
          name: erlang-solutions
          baseurl: 'http://packages.erlang-solutions.com/rpm/centos/$releasever/$basearch'
          gpgcheck: 0
          gpgkey: 'http://packages.erlang-solutions.com/debian/erlang_solutions.asc'
