---

galaxy_info:
  author: Jiri Tyr
  description: A role that installs Redis
  license: MIT
  min_ansible_version: 1.8
  platforms:
    - name: EL
      versions:
        - 6
  categories:
    - database:nosql
dependencies: 
  - role: common/yumrepo
    yumrepo_repos:
      yum_install:
        epel:
          name: epel-release
