---

- name: Manage Sensu client checks
  template:
    src: check.json.j2
    dest: /etc/sensu/conf.d/checks.json
  when: sensu_manage_checks
  notify:
    - Restart sensu-client
  tags:
    - sensu_checks
